---
# this docker-compose is for running a production-like instance of the quotes app
services:
  frontend:
    image: ghcr.io/efi-hacking/quotes-flask-frontend:release
    container_name: frontend
    ports: [5000:5000]
    restart: always
    environment:
      ENABLE_KUBERNETES_FEATURES: 'false'  # disable k8s specific functionality
      BACKEND_HOST: backend
      BACKEND_PORT: 5000

  backend:
    image: ghcr.io/efi-hacking/quotes-flask-backend:release
    container_name: backend
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: superuser
      DB_PASSWORD: complicated
      DB_NAME: quotes

  postgres:
    container_name: postgres
    image: postgres:14.3
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: complicated
      POSTGRES_DB: quotes
    volumes: [postgres:/var/lib/postgresql/data]

volumes:
  postgres:
